### ISSUE TITLE
If the value of the prop is an empty array, it treats it as a string.

### ISSUE THREAD

**Issue by sumancc** [DeloitteDigitalAPAC/react-habitat#3]
The issue is on this line of code: https://github.com/DeloitteDigitalAPAC/react-habitat/blob/ccf48dfa1ebfbe524934682caa85fd535424dd6c/src/Habitat.js#L62

For an empty array, the json representation would be `'[]'`, whose length is 2, but the logic on this line of code does a `JSON.parse` only if the length of the string is greater than 2.

**Comment by jennasalau** [comment]
Thank you for raising the issue @sumancc :)

I've now confirmed this bug with a failing test.

We will get onto a patch promptly.

Thanks
Jenna

**Comment by jennasalau** [comment]
This is now resolved in v0.3.0

**Comment by sumancc** [comment]
@jennasalau Thanks for fixing this promptly. Appreciate it!
