### ISSUE TITLE
Editable prop names

### ISSUE THREAD

**Issue by robmoorman** [DeloitteDigitalAPAC/react-habitat#38]
Hi there,

First of all thanks for open-sourcing this nifty project!

I stumbled upon some runtime issues while testing the data-props/data-components on a large variant of websites. To make this library more isolated within existing platforms it would be nice to make the names of the data attributes editable in order to prevent conflicts with existing JS functionalities on other platforms.

E.g. adding a prefix `data-myapp-component`.

Please let me know if there is any interest for this 👍

**Comment by jennasalau** [comment]
Hi @robmoorman,

I think thats an excellent suggestion.

We actually already have the ability to [configure components query selector](https://github.com/DeloitteDigitalAPAC/react-habitat#changing-the-habitat-query-selector).

Just need to extend the pattern to prop selectors too.

Is this something you are interested in putting in a PR for?

I have some refactoring already lined up on develop branch. If you do want to, please fork and branch from develop.

**Comment by robmoorman** [comment]
Hi @jennasalau ah thanks this is what I was looking for actually. I'll have a look if this fits the idea... if not I'll see I can create a PR for this based on the latest develop branch changes!

Thanks
