### ISSUE TITLE
CSS modules

### ISSUE THREAD

**Issue by moimikey** [DeloitteDigitalAPAC/react-habitat#7]
This isn't an issue, but I was curious as to whether or not `react-habitat` was able to support something like css modules out of the box? i use `react-css-modules` extensively and wanted to know if it would mesh well with `react-habitat`

thanks

**Comment by jennasalau** [comment]
Hi @moimikey 

`react-habitat` will work `react-css-modules` no problem.

Basically `react-habitat` is a utility wrapper of `react-dom` and you can use any of your favourite frameworks with `React` as per normal :)
